### ISSUE TITLE
Send is not supported

### ISSUE THREAD

**Issue by curlysanders** [lingoda/domain-events#11]
Hi,

I've been implementing the outbox and have overcome several hurdles in the process. I finally thought this is it, it will work now, but alas I get a TransportException saying 'Send is not supported'.

I have the following configuration for the eventBus:

```
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - doctrine_transaction
```

Transports:
```
        transports:
            outbox: 'outbox://default'
```

Events are recorded correctly in the database.

This is domain_events.yaml:
```
lingoda_domain_events:
    message_bus_name: 'event.bus'
    enable_event_publisher: true
```

Any help would be appreciated, I realy like the bundle.
